resilience4j:
  ratelimiter:
    instances:
      UI_RATE_LIMITER:
        allow-health-indicator-to-fail: true
        event-consumer-buffer-size: 50
        limit-for-period: 30
        limit-refresh-period: 60s
        register-health-indicator: true
        subscribe-for-events: true
        timeout-duration: 0s
      API_RATE_LIMITER:
        allow-health-indicator-to-fail: true
        event-consumer-buffer-size: 50
        limit-for-period: 60
        limit-refresh-period: 60s
        register-health-indicator: true
        subscribe-for-events: true
        timeout-duration: 0s
    metrics:
      enabled: true
