server:
  port: ${PORT:8080}

resilience4j:
  ratelimiter:
    instances:
      RATE_LIMITER:
        allow-health-indicator-to-fail: true
        event-consumer-buffer-size: 50
        limit-for-period: 5
        limit-refresh-period: 5s
        register-health-indicator: true
        subscribe-for-events: true
        timeout-duration: 0s
    metrics:
      enabled: true
